USE labs2018; -- uncomment for BYOD
DROP TABLE IF EXISTS ACCOUNT cascade;
-- SET AUTOCOMMIT OFF
SET AUTOCOMMIT=0;
-- CONFIRM AUTOCOMMIT is OFF
SELECT @@AUTOCOMMIT;
-- SHOW SESSION STATUS LIKE 'autocommit';

-- DDL 
CREATE TABLE account 
(id INTEGER PRIMARY KEY, 
accounttype varchar(10),
balance decimal (8,2));
-- DDL IMPLICIT COMMIT
INSERT INTO ACCOUNT VALUES (1, 'Savings',5000), (2, 'Credit', -1100);
-- EXPLICIT COMMIT
COMMIT;
